baseurl = "https://lowf.at"
languageCode = "en-us"
title = "Lowfat Industries, LLC"
theme = "hugo-grapes"
enableEmoji = true

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "chat"
    name = "chat"
    url = "https://lowfat.slack.com/"
    weight = 20

  [[menu.main]]
    identifier = "fah"
    name = "folding@home"
    url = ""
    weight = 25

  [[menu.main]]
    identifier = "fah (stats)"
    name = "folding@home (stats)"
    url = "https://folding.extremeoverclocking.com/team_summary.php?s=&t=261811"
    weight = 27

  [[menu.main]]
    identifier = "prv"
    name = "private"
    url = "https://prv.lowf.at/"
    weight = 30


[params]
avatar = "img/icon.png"
